#!/bin/bash

REPO_ROOT='/home/git'

if [ -z ${SSH_ORIGINAL_COMMAND} ]; then
  # Attempting to start an interactive shell
  echo "Interactive shell now allowed"
  exit 10
fi


COMMAND=$(echo $SSH_ORIGINAL_COMMAND | cut -d ' ' -f 1)

case ${COMMAND} in
  git-receive-pack)
    ;;
  git-upload-archive)
    ;;
  git-upload-pack)
    ;;
  *)
    echo "no."
    exit 11
    ;;
esac

GITPATH=$(echo $SSH_ORIGINAL_COMMAND | cut -d ' ' -f 2 | sed s/\'//g)
GITPATH="${REPO_ROOT}/${GITPATH}"

realpath ${GITPATH} | grep -e "^${REPO_ROOT}" > /dev/null
if [ $? -ne 0 ]; then
  echo "Requested path outside of allowed path"
  exit 12
fi

$COMMAND "$GITPATH" < /dev/stdin
