#!/bin/bash

REPO_ROOT='/home/git'

if [ -z "${SSH_ORIGINAL_COMMAND}" ]; then
  # Attempting to start an interactive shell
  echo "Interactive shell now allowed" 1>&2
  exit 1
fi


COMMAND=$(echo ${SSH_ORIGINAL_COMMAND} | cut -d ' ' -f 1)

case ${COMMAND} in
  git-receive-pack)
    if [ "${1}" != "rw" ]; then 
      echo "Write Access Denied" 1>&2
      exit 1
    fi
    ;;
  git-upload-archive)
    ;;
  git-upload-pack)
    ;;
  *)
    echo "no." 1>&2
    exit 1
    ;;
esac

GITPATH=$(echo ${SSH_ORIGINAL_COMMAND} | cut -d ' ' -f 2 | sed s/\'//g)
GITPATH="${REPO_ROOT}/${GITPATH}"

realpath ${GITPATH} | grep -e "^${REPO_ROOT}" > /dev/null
if [ $? -ne 0 ]; then
  echo "Requested path outside of allowed path" 1>&2
  exit 1
fi

${COMMAND} "${GITPATH}" < /dev/stdin
